name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  schedule:
    - cron: "7 */2 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
      packages: read
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            EpexPredictor/requirements.txt

      - name: Install Python dependencies
        working-directory: EpexPredictor
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Generate BE forecast
        working-directory: EpexPredictor
        run: |
          python predictor/model/pricepredictor.py > ../forecast.json

      - name: Generate Ecopower prices
        run: "./ecopower_dynamisch.sh > ecopower.json"
      - run: "cp ecopower.json index.html"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
